### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by chuong** [NaturalHistoryMuseum/ALICE#23]
Thank you for open source your exciting work.
I try to install ALICE on Windows and have pip = 23.2.1 and Anaconda python=3.11, but have the following issue with "import torch".
I am not sure how to deal with this.

`
ALICE> pip install -r requirements.txt
Collecting craft_text_detector@ git+https://github.com/benscott/craft-text-detector (from -r requirements.txt (line 23))
  Cloning https://github.com/benscott/craft-text-detector to c:\users\chuong\appdata\local\temp\pip-install-8kss8xw5\craft-text-detector_ec435d6019314d54b161f18ec08f23e5
  Running command git clone --filter=blob:none --quiet https://github.com/benscott/craft-text-detector 'C:\Users\chuong\AppData\Local\Temp\pip-install-8kss8xw5\craft-text-detector_ec435d6019314d54b161f18ec08f23e5'
  Resolved https://github.com/benscott/craft-text-detector to commit d591c12bd24347f11527c229b409452f93141084
  Preparing metadata (setup.py) ... done
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@ff53992b1985b63bd3262b5a36167098e3dada02 (from -r requirements.txt (line 24))
  Cloning https://github.com/facebookresearch/detectron2.git (to revision ff53992b1985b63bd3262b5a36167098e3dada02) to c:\users\chuong\appdata\local\temp\pip-install-8kss8xw5\detectron2_8814346b27e1450f992f512fc2835a88
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\chuong\AppData\Local\Temp\pip-install-8kss8xw5\detectron2_8814346b27e1450f992f512fc2835a88'
  Running command git rev-parse -q --verify 'sha^ff53992b1985b63bd3262b5a36167098e3dada02'
  Running command git fetch -q https://github.com/facebookresearch/detectron2.git ff53992b1985b63bd3262b5a36167098e3dada02
  Running command git checkout -q ff53992b1985b63bd3262b5a36167098e3dada02
  Resolved https://github.com/facebookresearch/detectron2.git to commit ff53992b1985b63bd3262b5a36167098e3dada02
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\chuong\AppData\Local\Temp\pip-install-8kss8xw5\detectron2_8814346b27e1450f992f512fc2835a88\setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by chuong** [comment]
I also try to install under Ubuntu with Anaconda python=3.9 and pip=24.2 and get similar error

$ pip install -r requirements.txt
Collecting craft_text_detector@ git+https://github.com/benscott/craft-text-detector (from -r requirements.txt (line 24))
  Cloning https://github.com/benscott/craft-text-detector to /tmp/pip-install-yc4th76o/craft-text-detector_30b0d4f43f38413da005d5161bc4cee3
  Running command git clone --filter=blob:none --quiet https://github.com/benscott/craft-text-detector /tmp/pip-install-yc4th76o/craft-text-detector_30b0d4f43f38413da005d5161bc4cee3
  Resolved https://github.com/benscott/craft-text-detector to commit d591c12bd24347f11527c229b409452f93141084
  Preparing metadata (setup.py) ... done
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@ff53992b1985b63bd3262b5a36167098e3dada02 (from -r requirements.txt (line 25))
  Cloning https://github.com/facebookresearch/detectron2.git (to revision ff53992b1985b63bd3262b5a36167098e3dada02) to /tmp/pip-install-yc4th76o/detectron2_f2fd61e4a19c457a9cbe8e941e738efa
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-yc4th76o/detectron2_f2fd61e4a19c457a9cbe8e941e738efa
  Running command git rev-parse -q --verify 'sha^ff53992b1985b63bd3262b5a36167098e3dada02'
  Running command git fetch -q https://github.com/facebookresearch/detectron2.git ff53992b1985b63bd3262b5a36167098e3dada02
  Running command git checkout -q ff53992b1985b63bd3262b5a36167098e3dada02
  Resolved https://github.com/facebookresearch/detectron2.git to commit ff53992b1985b63bd3262b5a36167098e3dada02
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yc4th76o/detectron2_f2fd61e4a19c457a9cbe8e941e738efa/setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
